name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup DITA
      run: wget https://github.com/dita-ot/dita-ot/releases/download/3.4/dita-ot-3.4.zip && unzip dita-ot-3.4.zip
    - run: echo "::add-path::./dita-ot-3.4/bin"
    - name: Vale
      uses: errata-ai/vale-action@v1.2.0
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}