name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    - run: mkdir vale && cd vale
    - run: curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s latest
    - run: echo "./bin" >> $GITHUB_PATH
    - name: Setup DITA
      run: wget https://github.com/dita-ot/dita-ot/releases/download/3.5.4/dita-ot-3.5.4.zip
    - run: unzip dita-ot-3.5.4.zip
    - run: echo "./dita-ot-3.5.4/bin" >> $GITHUB_PATH
    - run: cd ..
    - run: vale -v
    - run: ls
    - run: vale --output=JSON --glob '*.dita' topics | node ci-lint.js
