name: Release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            For a full list of changes,
            see the [changelog](https://github.com/TelestionTeam/telestion-docs/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false
  build-and-upload-artifacts:
    name: Upload artifacts
    needs:
      - create-release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build-configs/out/*.pdf
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
